<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-02-14T15:54:06Z" name="Suite" finished-at="2019-02-14T15:54:06Z" duration-ms="64">
    <groups>
    </groups>
    <test started-at="2019-02-14T15:54:06Z" name="Test" finished-at="2019-02-14T15:54:06Z" duration-ms="64">
      <class name="com.outlook.qa.testcases.MailBoxPageTest">
        <test-method is-config="true" signature="reporting()[pri:0, instance:com.outlook.qa.testcases.MailBoxPageTest@bcec361]" started-at="2019-02-14T15:54:06Z" name="reporting" finished-at="2019-02-14T15:54:06Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.outlook.qa.testcases.MailBoxPageTest.reporting(MailBoxPageTest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:543)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:212)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:637)
	at org.testng.TestRunner.run(TestRunner.java:605)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.outlook.qa.testcases.MailBoxPageTest@bcec361]" started-at="2019-02-14T15:54:06Z" name="setUp" finished-at="2019-02-14T15:54:06Z" duration-ms="0" status="SKIP">
        </test-method>
        <test-method signature="loginTest()[pri:1, instance:com.outlook.qa.testcases.MailBoxPageTest@bcec361]" started-at="2019-02-14T15:54:06Z" name="loginTest" finished-at="2019-02-14T15:54:06Z" duration-ms="1" status="SKIP">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
